### ISSUE TITLE
target="_blank" is actually bad in this case

### ISSUE THREAD

**Issue by theZorro266** [Vaygrim/vaygrim.github.io#3]
If you are browsing on one webpage, a new window is always confusing to the user. If the user really wants to have a new window/tab for a page, he needs to use his browser.
The target for a new window/tab should only be used on links to external websites, where you want the user to return, after he visited that site.

That is general web convention and my opinion. Giving feedback is also my job on this, so there you go :)

**Comment by Vaygrim** [comment]
Apparently I left this open for a year. Whoops!
